/**
 * General questions that any structure can answer in the "Ask me" chat,
 * and that appear in the library.
 */
export const FAQ = [
  { q: 'What is glaucoma?', a: 'A group of eye diseases that slowly damage the optic nerve — the cable connecting the eye to the brain. The nerve fibres die in a typical pattern, the optic disc becomes "cupped", and vision is lost, usually starting at the edges. Eye pressure is the main risk factor that can be treated.', k: 'what is glaucoma definition meaning' },
  { q: 'How does high eye pressure damage the optic nerve?', a: 'Pressure inside the eye pushes on the whole eye wall, and the weakest spot is where the optic nerve leaves: a sieve-like plate called the lamina cribrosa. Under strain it bows backwards, pinching the nerve fibres and their blood supply and blocking the transport of essential molecules along them. The affected ganglion cells eventually die — permanently.', k: 'pressure damage optic nerve how mechanism lamina harm' },
  { q: 'Can glaucoma be cured?', a: 'Lost vision cannot be restored, because the optic nerve does not regenerate. But glaucoma can almost always be controlled: lowering eye pressure slows or stops further damage. With early detection and treatment, most people keep useful vision for life.', k: 'cure curable reverse heal fix permanent' },
  { q: 'Why is it called the silent thief of sight?', a: 'Most glaucoma causes no pain and no redness, and it takes the side vision first. The brain fills in missing patches and the other eye compensates, so people usually notice only when a lot of nerve is already gone.', k: 'silent thief sight why called' },
  { q: 'Does glaucoma hurt?', a: 'Usually not. The common types (open-angle, normal-tension) are completely painless. The exception is an acute angle-closure attack, which causes sudden severe pain, a red eye, halos and nausea — an emergency.', k: 'hurt pain painful' },
  { q: 'Will I go blind?', a: 'Most people with glaucoma do not go blind. The risk is highest when it is found late or treatment is not followed. Using drops as prescribed and keeping follow-up appointments are the most powerful things a patient can do.', k: 'blind blindness go lose sight' },
  { q: 'Is glaucoma hereditary?', a: 'It often runs in families. Having a parent, brother or sister with glaucoma raises your risk several-fold — so tell your relatives if you are diagnosed. Some genes (such as MYOC, CYP1B1, LOXL1) are known, but most glaucoma involves many genes plus age and other factors.', k: 'hereditary genetic family inherit genes runs' },
  { q: 'What does glaucoma vision look like?', a: 'Not like a black tunnel! Missing areas are usually not seen as dark — the brain fills them in with surrounding colours and patterns, so objects can simply be "not there": a step, a car from the side, a word on a page. Use "See through the patient’s eyes" in the Glaucoma Lab and compare the realistic and the "show missing areas" modes.', k: 'vision look like see tunnel black' },
  { q: 'Is high eye pressure the same as glaucoma?', a: 'No. High pressure without nerve damage is called ocular hypertension — a risk factor. And glaucoma can occur with normal pressure (normal-tension glaucoma). Glaucoma is defined by damage to the optic nerve.', k: 'high pressure same ocular hypertension' },
  { q: 'Can I prevent glaucoma?', a: 'You cannot change your age or genes, but you can prevent glaucoma blindness: get regular comprehensive eye exams, know your family history, use prescribed treatment, protect your eyes from injury, and tell your doctor about long-term steroid use.', k: 'prevent avoid stop risk lower' },
  { q: 'How often should I get my eyes checked?', a: 'It depends on your age and risk. Many eye-care organisations suggest a baseline comprehensive exam around 40, and more frequent exams as you get older or if you have risk factors (family history, African ancestry, high pressure, high myopia, diabetes, steroid use). Ask your eye-care professional what is right for you.', k: 'how often check exam test screening when' },
  { q: 'Can children get glaucoma?', a: 'Yes, though it is rare. Babies can be born with a malformed drain (primary congenital glaucoma), causing big, cloudy, watery, light-sensitive eyes. Children can also develop glaucoma after eye surgery, injury or with some syndromes. Early surgery can save vision.', k: 'children child baby kids young' },
  { q: 'Do screens or reading cause glaucoma?', a: 'No — there is no good evidence that screen use or reading causes glaucoma. (Screens can cause tired, dry eyes, which is a different thing.)', k: 'screen phone computer reading cause' },
  { q: 'Can lifestyle help?', a: 'Regular aerobic exercise can lower eye pressure slightly, and a healthy lifestyle supports blood flow. Some activities raise pressure temporarily — such as long head-down yoga positions or very tight swimming goggles. But lifestyle does not replace treatment; talk to your doctor before changing anything.', k: 'lifestyle exercise diet food yoga coffee' },
  { q: 'Does cannabis treat glaucoma?', a: 'Cannabis lowers eye pressure only for about 3–4 hours, so it would have to be used around the clock, with side effects (and it may lower blood pressure, reducing blood flow to the optic nerve). Major glaucoma organisations do not recommend it as a treatment.', k: 'cannabis marijuana weed thc' },
  { q: 'Can I drive with glaucoma?', a: 'Many people with glaucoma drive safely. Driving rules depend on the visual field in both eyes and differ by country. Your eye doctor can tell you whether your field meets the legal standard.', k: 'drive driving car licence license' },
  { q: 'Why do I need to use drops when I feel fine?', a: 'Because glaucoma has no symptoms to warn you. The drops work in the background, keeping pressure in a safe range. Missing drops lets pressure rise again — and the nerve damage that follows is permanent and unfelt.', k: 'drops why feel fine adherence stop' },
  { q: 'What is the most important test for glaucoma?', a: 'There isn\'t a single one. A diagnosis combines the optic disc examination, OCT of the nerve fibres, visual fields, pressure, corneal thickness and gonioscopy — and then watches for change over time.', k: 'test important best diagnose diagnosis' },
];

export const DISCLAIMER = `Glaucoma Explorer is an educational project. It simplifies anatomy and uses an illustrative model — it is not a medical device and not medical advice. Always talk to an eye-care professional about your own eyes.`;
