/**
 * GUIDED TOURS
 * Each step flies the camera somewhere (view id or explicit pos/target), can highlight a
 * part, set the simulation, and can ask the visitor to PREDICT before revealing the answer.
 */
export const TOURS = [
  {
    id: 'drop',
    name: 'The journey of a drop',
    blurb: 'Follow a droplet of fluid from the tap to the drain — the key to understanding glaucoma.',
    minutes: 4,
    steps: [
      {
        title: 'A pressurised eye',
        view: 'overview',
        text: `<p>Your eye is a ball of living tissue kept firm by fluid, like a football kept firm by air. But unlike a football, the fluid is <strong>constantly replaced</strong>: produced on one side, drained on the other.</p><p>The glowing droplets you see are that fluid — <strong>aqueous humour</strong>. Let's follow one.</p>`,
        flow: true,
        sim: 'healthy',
      },
      {
        title: 'The tap: ciliary processes',
        view: 'ciliary-processes',
        highlight: 'ciliary-processes',
        text: `<p>We're looking forward from inside the eye, at the back of the lens. The ring of folds around it — glowing while they work — are the <strong>ciliary processes</strong>. They filter blood plasma and pump out about <strong>2.5&nbsp;microlitres</strong> of crystal-clear fluid every minute, day and night.</p>`,
        flow: true,
      },
      {
        title: 'Behind the iris',
        view: 'posterior-chamber',
        highlight: 'iris',
        text: `<p>Fresh fluid collects in the narrow <strong>posterior chamber</strong> behind the iris. To move on, it must squeeze through the tight gap where the iris rests on the lens — at the edge of the <strong>pupil</strong>.</p>`,
        flow: true,
      },
      {
        title: 'Into the anterior chamber',
        view: 'anterior-chamber',
        highlight: 'cornea',
        text: `<p>Through the pupil, the fluid enters the <strong>anterior chamber</strong> behind the cornea. Here it feeds the cornea and lens — which have no blood vessels — and slowly circulates: warmed by the iris, cooled by the cornea.</p>`,
        flow: true,
      },
      {
        title: 'Predict first',
        view: 'anterior-chamber',
        text: `<p>The ciliary body keeps producing fluid every second. Imagine the drain slowly clogs, but the tap keeps running…</p>`,
        predict: {
          q: 'What happens to the pressure inside the eye?',
          options: ['It drops — less fluid is moving', 'It rises — fluid builds up until it is forced out', 'Nothing — the eye just makes less fluid'],
          answer: 1,
          explain: 'The tap does not "know" the drain is clogged — production barely changes. Fluid accumulates until the pressure is high enough to push the same volume out through the narrower drain. A new balance is reached, at a higher pressure. This is exactly what happens in open-angle glaucoma.',
        },
        flow: true,
      },
      {
        title: 'The drain: trabecular meshwork',
        view: 'drainage-angle',
        highlight: 'trabecular-meshwork',
        cut: true,
        text: `<p>The fluid drifts to the <strong>drainage angle</strong>, where the iris meets the cornea all the way round the eye. There it filters through the <strong>trabecular meshwork</strong>, a spongy living sieve. The resistance of this sieve is what sets your eye pressure.</p>`,
        flow: true,
      },
      {
        title: "Schlemm's canal",
        view: 'schlemms-canal',
        highlight: 'schlemms-canal',
        text: `<p>Behind the meshwork lies <strong>Schlemm's canal</strong>, a ring-shaped channel circling the eye. The droplets travel along it to collector channels, then out into the <strong>episcleral veins</strong> on the surface of the eye — back into the bloodstream.</p>`,
        flow: true,
      },
      {
        title: 'The back door',
        view: 'uveoscleral-pathway',
        highlight: 'ciliary-body',
        text: `<p>Some droplets take a different exit: they seep between the fibres of the ciliary muscle into the space behind it — the <strong>uveoscleral pathway</strong>. The most widely used glaucoma drops, prostaglandin analogues, work by widening this back door.</p>`,
        flow: true,
      },
      {
        title: 'Now break the drain',
        view: 'drainage-angle',
        highlight: 'trabecular-meshwork',
        sim: 'poag',
        simTime: 14,
        text: `<p>This is the same eye with <strong>primary open-angle glaucoma</strong>. The angle is still wide open — but the meshwork has become stiff and clogged. Watch the droplets queue and turn amber. The pressure gauge rises.</p><p>Next: where does this pressure do its damage? Take the tour <em>“How glaucoma steals sight”</em>, or experiment in the <strong>Glaucoma Lab</strong>.</p>`,
        flow: true,
      },
    ],
  },
  {
    id: 'sight',
    name: 'From light to sight',
    blurb: 'Fly the path of light through the eye to the retina and the optic nerve.',
    minutes: 4,
    steps: [
      {
        title: 'The window',
        view: 'cornea',
        highlight: 'cornea',
        sim: 'healthy',
        text: `<p>Light first meets the <strong>cornea</strong>, the clear dome at the front. It does about two-thirds of the eye's focusing — and has no blood vessels at all, so it stays transparent.</p>`,
      },
      {
        title: 'The aperture',
        view: 'iris',
        highlight: 'iris',
        text: `<p>The <strong>iris</strong> is a ring of muscle that widens or narrows the <strong>pupil</strong> to control how much light gets in — like a camera aperture. Its colour comes from the pigment melanin.</p>`,
      },
      {
        title: 'The fine focus',
        view: 'lens',
        highlight: 'lens',
        cut: true,
        text: `<p>Behind the iris hangs the <strong>lens</strong>, suspended by hundreds of fine zonule fibres. The ciliary muscle changes its shape to focus near or far. It keeps growing all your life — which matters for angle-closure glaucoma.</p>`,
      },
      {
        title: 'Across the vitreous',
        view: 'vitreous',
        text: `<p>Light now crosses the <strong>vitreous</strong>, a clear gel filling most of the eye. The specks drifting around you are floaters — clumps of collagen whose shadows you sometimes see in your own vision.</p>`,
      },
      {
        title: 'The retina',
        view: 'retina',
        highlight: 'retina',
        text: `<p>The image lands on the <strong>retina</strong>, a sheet of brain tissue lining the back wall. Its photoreceptors convert light into electrical signals. The glowing threads are bundles of nerve fibres from the <strong>retinal ganglion cells</strong> — the pulses travelling along them represent signals heading for the brain.</p>`,
      },
      {
        title: 'The macula',
        view: 'macula',
        highlight: 'macula',
        text: `<p>The darker area is the <strong>macula</strong>, with the tiny <strong>fovea</strong> in its centre: the spot of sharpest vision. Notice how the nerve fibres curve around it instead of crossing it.</p>`,
      },
      {
        title: 'Predict first',
        view: 'rnfl',
        highlight: 'rnfl',
        text: `<p>All the nerve fibres of the retina converge on one spot and leave the eye together.</p>`,
        predict: {
          q: 'What do you expect to see where the fibres leave the eye?',
          options: ['The sharpest vision, because all fibres meet there', 'A blind spot, because there is no room for photoreceptors', 'A second macula'],
          answer: 1,
          explain: 'Where the nerve exits, there are no photoreceptors — so every eye has a natural blind spot, about 15° to the side of where you look. You never notice it, because the other eye and your brain fill it in.',
        },
      },
      {
        title: 'The optic disc',
        view: 'optic-disc',
        highlight: 'optic-disc',
        text: `<p>This is the <strong>optic disc</strong>: about 1.2 million fibres dive through it. The orange-pink ring is the living <strong>rim</strong> of nerve fibres; the pale hollow in the middle is the <strong>cup</strong>. Vessels feeding the retina enter and leave through its centre.</p>`,
      },
      {
        title: 'The cable to the brain',
        view: 'optic-nerve',
        highlight: 'optic-nerve',
        text: `<p>Behind the eye, the fibres form the <strong>optic nerve</strong>, which runs to the brain. Like the brain itself, it cannot regenerate. This is the structure glaucoma damages.</p>`,
      },
    ],
  },
  {
    id: 'thief',
    name: 'How glaucoma steals sight',
    blurb: 'Pressure, the optic nerve, dying fibres, and the vision you lose without noticing.',
    minutes: 5,
    steps: [
      {
        title: 'A pressure problem at the front…',
        view: 'drainage-angle',
        highlight: 'trabecular-meshwork',
        cut: true,
        sim: 'poag',
        simTime: 6,
        text: `<p>In open-angle glaucoma the drain slowly clogs and pressure rises. But the drain is at the <strong>front</strong> of the eye…</p>`,
        flow: true,
      },
      {
        title: 'Predict first',
        view: 'section',
        text: `<p>…and the damage happens at the <strong>back</strong>, at the optic nerve.</p>`,
        predict: {
          q: 'Why would a drain problem at the front damage the nerve at the back?',
          options: ['The fluid flows backwards and poisons the nerve', 'Pressure pushes equally in all directions, and the weakest spot in the wall is where the nerve leaves the eye', 'The drain is connected to the nerve by blood vessels'],
          answer: 1,
          explain: 'Pressure in a closed ball pushes on every part of the wall equally (Pascal\'s principle). Almost everywhere the wall is solid sclera — but where the optic nerve exits, it is a sieve: the lamina cribrosa. That sieve deforms under pressure, pinching the nerve fibres and their blood supply.',
        },
      },
      {
        title: 'The weak spot',
        view: 'lamina-cribrosa',
        highlight: 'lamina-cribrosa',
        sim: 'poag',
        simTime: 6,
        damage: 0.15,
        text: `<p>At the bottom of the optic disc lies the <strong>lamina cribrosa</strong>, a sieve of collagen plates. All 1.2 million fibres squeeze through its pores. Its pores are biggest at the top and bottom — and that is where fibres are lost first.</p>`,
      },
      {
        title: 'Fibres begin to die',
        view: 'rnfl',
        highlight: 'rnfl',
        sim: 'poag',
        simTime: 12,
        damage: 0.45,
        text: `<p>Years pass. Watch the glowing fibres: the bundles entering the <strong>bottom and top</strong> of the disc flash red and go dark. Each line stands for thousands of ganglion cell axons. They will not grow back.</p>`,
      },
      {
        title: 'The cup grows',
        view: 'optic-disc',
        highlight: 'optic-disc',
        damage: 0.7,
        text: `<p>With fewer fibres, the pink rim thins and the pale cup <strong>widens and deepens</strong> — vertically first. The pores of the lamina appear at its floor. This "cupping" is what eye doctors look for when they examine the optic disc.</p>`,
      },
      {
        title: 'Predict first',
        view: 'optic-disc',
        damage: 0.7,
        text: `<p>This person has lost a large share of their nerve fibres.</p>`,
        predict: {
          q: 'Would they have noticed anything wrong with their vision?',
          options: ['Yes — the world would look dark and patchy', 'Probably not — the brain fills in gaps and central vision is still sharp', 'Yes — their eye would hurt'],
          answer: 1,
          explain: 'Glaucoma usually takes peripheral vision first, the brain fills in missing areas, and the other eye covers for the damaged one. Central vision often stays sharp until late. That is why it is called the silent thief of sight — and why regular eye exams matter.',
        },
      },
      {
        title: 'Through their eyes',
        view: 'overview',
        damage: 0.7,
        vision: true,
        text: `<p>This overlay shows roughly what this patient's eye can still see: arch-shaped areas above and below are faded, with a sharp horizontal edge on the nose side — a <strong>nasal step</strong>. The pattern comes straight from which nerve fibres died.</p><p>Real patients don't see dark patches; their brain fills them in — things just aren't there.</p>`,
      },
      {
        title: 'How it is caught',
        view: 'optic-disc',
        damage: 0.25,
        vision: false,
        text: `<p>Early glaucoma can be found long before the patient notices anything, by combining tests: an <strong>optic disc exam</strong>, an <strong>OCT scan</strong> measuring the nerve fibre layer, a <strong>visual field test</strong>, <strong>pressure</strong>, corneal thickness and <strong>gonioscopy</strong> of the angle. Visit the <em>Diagnosis Clinic</em> to try them on this virtual patient.</p>`,
      },
      {
        title: 'Stopping the thief',
        view: 'drainage-angle',
        cut: true,
        sim: 'poag',
        simTime: 12,
        treat: ['prostaglandin'],
        damage: 0.25,
        flow: true,
        text: `<p>Treatment lowers the pressure: here a prostaglandin drop opens the back door, and the droplets flow again. Damage that has happened stays — but further loss slows or stops. <strong>Found early, glaucoma rarely leads to blindness.</strong></p><p>Now open the <strong>Glaucoma Lab</strong> and try to save a patient's vision yourself.</p>`,
      },
    ],
  },
];
